name: Bug Report
description: File a bug report
body:
  - type: checkboxes
    attributes:
      label: Check for existing issues
      description: Check existing issues to avoid creating duplicates; if an issue already exists, place react on it (👍) instead.
      options:
        - label: Completed
          required: true
  - type: textarea
    attributes:
      label: Describe the bug / provide steps to reproduce it
      description: A clear and concise description of what the bug is.
    validations:
      required: true
